replicaCount: 1

fullname: goduckbot
name: goduckbot

image:
  repository: wcatz/goduckbot
  pullPolicy: IfNotPresent
  tag: "latest"

resources: {}

config:
  poolId: ""
  ticker: ""
  poolName: ""
  nodeAddress:
    host1: ""
    # optional
    host2: ""
  networkMagic: 764824073

  telegram:
    token: ""
    channel: ""

  twitter:
    bearer_token: ""
    api_key: ""
    api_key_secret: ""
    access_token: ""
    access_token_secret: ""
    client_id: ""
    client_secret: ""

  leaderlog:
    enabled: false
    vrfKeyPath: "/keys/vrf.skey"
    timezone: "UTC"

  database:
    host: "k3s-postgres-rw.postgres.svc.cluster.local"
    port: 5432
    name: "goduckbot"
    user: "goduckbot"
    password: ""

vrfKey:
  enabled: false
  secretName: ""
  mountPath: "/keys"
