# .github/dependabot.yml
version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly" # or "daily", "monthly"
    open-pull-requests-limit: 5
    # Allow manually triggering via GitHub UI (enabled by default)
    allow:
      - dependency-type: "all"