apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.fullname }}
  labels:
    app.kubernetes.io/name: {{ .Values.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      containers:
        - name: {{ .Values.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: TELEGRAM_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.fullname }}-secrets
                  key: TELEGRAM_TOKEN
            - name: TWITTER_BEARER_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.fullname }}-secrets
                  key: TWITTER_BEARER_TOKEN
            - name: TWITTER_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.fullname }}-secrets
                  key: TWITTER_API_KEY
            - name: TWITTER_API_KEY_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.fullname }}-secrets
                  key: TWITTER_API_KEY_SECRET
            - name: TWITTER_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.fullname }}-secrets
                  key: TWITTER_ACCESS_TOKEN
            - name: TWITTER_ACCESS_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.fullname }}-secrets
                  key: TWITTER_ACCESS_TOKEN_SECRET
            - name: TWITTER_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.fullname }}-secrets
                  key: TWITTER_CLIENT_ID
            - name: TWITTER_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.fullname }}-secrets
                  key: TWITTER_CLIENT_SECRET
            {{- if .Values.config.leaderlog.enabled }}
            - name: GODUCKBOT_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.fullname }}-secrets
                  key: GODUCKBOT_DB_PASSWORD
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: config-volume
              mountPath: /app/config.yaml
              subPath: config.yaml
              readOnly: true
            {{- if .Values.vrfKey.enabled }}
            - name: vrf-key
              mountPath: {{ .Values.vrfKey.mountPath }}
              readOnly: true
            {{- end }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ .Values.fullname }}-config
            items:
              - key: config.yaml
                path: config.yaml
        {{- if .Values.vrfKey.enabled }}
        - name: vrf-key
          secret:
            secretName: {{ .Values.vrfKey.secretName }}
        {{- end }}
      restartPolicy: Always
